{{- $portRange := untilStep (int .Values.ports.from) (int (add1 .Values.ports.to)) 1 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coturn.fullname" . }}
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3478
      targetPort: turn-3478
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 3478
      {{- end }}
      protocol: UDP
      name: turn-3478
    {{- range $portRange }}
    - port: {{ . }}
      targetPort: {{ . }}
      {{- if eq $.Values.service.type "NodePort" }}
      nodePort: {{ . }}
      {{- end }}
      protocol: UDP
      name: turn-{{ . }}
    {{- end }}
  selector:
    {{- include "coturn.selectorLabels" . | nindent 4 }}
