apiVersion: v1
kind: Service
metadata:
  name: {{ include "back.fullname" . }}
  labels:
    {{- include "back.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "back.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "back.fullname" . }}-ws
  labels:
    {{- include "back.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceWs.type }}
  ports:
    - port: {{ .Values.serviceWs.port }}
      targetPort: direct
      protocol: TCP
      name: direct
  selector:
    {{- include "back.selectorLabels" . | nindent 4 }}
