{{- if .Values.prometheus.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pusher.fullname" . }}
  labels:
    {{- include "pusher.labels" . | nindent 4 }}
  {{- if .Values.prometheus.monitor.additionalLabels }}
    {{- toYaml .Values.prometheus.monitor.additionalLabels | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ default "app.kubernetes.io/name" .Values.prometheus.monitor.jobLabel }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
    {{- if .Values.prometheus.monitor.selectorOverride }}
      {{ toYaml .Values.prometheus.monitor.selectorOverride | indent 6 }}
    {{ else }}
      app: {{ include "pusher.fullname" . }}
      release: {{ .Release.Name }}
    {{- end }}
  endpoints:
    - port: {{ .Values.service.portName }}
      scheme: {{ .Values.prometheus.monitor.scheme }}
      path: {{ .Values.prometheus.monitor.path }}
    {{- with .Values.prometheus.monitor.basicAuth }}
      basicAuth:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.prometheus.monitor.bearerTokenFile }}
      bearerTokenFile: {{ . }}
    {{- end }}
    {{- if .Values.env.PROMETHEUS_AUTHORIZATION_TOKEN }}
      bearerTokenSecret:
        key: token
        name: {{ include "pusher.fullname" . }}-prometheus-token
    {{- end }}
    {{- with .Values.prometheus.monitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.prometheus.monitor.proxyUrl }}
      proxyUrl: {{ . }}
    {{- end }}
    {{- with .Values.prometheus.monitor.interval }}
      interval: {{ . }}
    {{- end }}
    {{- with .Values.prometheus.monitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
    {{- end }}
    {{- with .Values.prometheus.monitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.prometheus.monitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
---
{{- if .Values.env.PROMETHEUS_AUTHORIZATION_TOKEN }}
apiVersion: v1
metadata:
  name: {{ include "pusher.fullname" . }}-prometheus-token
data:
  token: {{ .Values.env.PROMETHEUS_AUTHORIZATION_TOKEN | b64enc | quote }}
kind: Secret
{{- end }}
