# Default values for n8n.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

master:
  env:
  image:
    repository: n8nio/n8n
    tag: "0.164.1"
  ingress:
    enabled: true
    hosts:
      - host: master.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: master-tls
        hosts:
          - master.local
  replicaCount: 1
webhook:
  image:
    repository: n8nio/n8n
    tag: "0.164.1"
  ingress:
    enabled: true
    hosts:
      - host: webhook.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: webhook-tls
        hosts:
          - webhook.local
  replicaCount: 1
worker:
  env:
  image:
    epository: n8nio/n8n
    tag: "0.164.1"
  ingress:
    enabled: true
    hosts:
      - host: worker.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: worker-tls
        hosts:
          - worker.local
  replicaCount: 1