apiVersion: v1
kind: Service
metadata:
  name: {{ include "back.fullname" . }}
  labels:
    {{- include "back.labels" . | nindent 4 }}
    {{- toYaml .Values.service.additionalLabels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "back.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "back.fullname" . }}-ws
  labels:
    {{- include "back.labels" . | nindent 4 }}
    {{- toYaml .Values.serviceWs.additionalLabels | nindent 4 }}
spec:
  type: {{ .Values.serviceWs.type }}
  ports:
    - port: {{ .Values.serviceWs.port }}
      targetPort: {{ .Values.serviceWs.portName }}
      protocol: TCP
      name: {{ .Values.serviceWs.portName }}
  selector:
    {{- include "back.selectorLabels" . | nindent 4 }}
