apiVersion: v1
kind: Service
metadata:
  name: {{ include "back.fullname" . }}
  labels:
    {{- include "back.labels" . | nindent 4 }}
    {{- with .Values.service.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "back.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "back.fullname" . }}-ws
  labels:
    {{- include "back.labels" . | nindent 4 }}
    {{- with .Values.serviceWs.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.serviceWs.type }}
  ports:
    - port: {{ .Values.serviceWs.port }}
      targetPort: {{ .Values.serviceWs.portName }}
      protocol: TCP
      name: {{ .Values.serviceWs.portName }}
  selector:
    {{- include "back.selectorLabels" . | nindent 4 }}
