# Default values for pusher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: thecodingmachine/workadventure-pusher
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  ADMIN_API_TOKEN:
  ADMIN_API_URL:
  ADMIN_SOCKETS_TOKEN:
  ADMIN_URL:
  ALLOW_ARTILLERY:
  API_URL: "workadventure-back-ws:50051"
  CPU_OVERHEAT_THRESHOLD:
  DISABLE_ANONYMOUS: false
  FRONT_URL: "https://play.workadventure.local"
  JITSI_ISS:
  JITSI_URL:
  OPID_CLIENT_ID:
  OPID_CLIENT_ISSUER:
  OPID_CLIENT_REDIRECT_URL:
  OPID_CLIENT_SECRET:
  OPID_LOCALE_CLAIM:
  OPID_PROFILE_SCREEN_PROVIDER:
  OPID_SCOPE:
  OPID_USERNAME_CLAIM:
  PUSHER_HTTP_PORT:
  SECRET_JITSI_KEY:
  SECRET_KEY:
  SOCKET_IDLE_TIMER:

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 100m
     memory: 200Mi
   requests:
     cpu: 100m
     memory: 150Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
